// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW6LEeWDgS85UxzlSZ0aHBL1hji5eDX8g',
    appId: '1:757179767968:web:b565b06d1f482562337dc5',
    messagingSenderId: '757179767968',
    projectId: 'khabi-naa',
    authDomain: 'khabi-naa.firebaseapp.com',
    databaseURL: 'https://khabi-naa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'khabi-naa.firebasestorage.app',
    measurementId: 'G-KS8RYLJ0FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJMJ26xlbZT5xji1pHulaOu_koMQ8XH0s',
    appId: '1:757179767968:android:03565612d2e78185337dc5',
    messagingSenderId: '757179767968',
    projectId: 'khabi-naa',
    databaseURL: 'https://khabi-naa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'khabi-naa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYR7hl3hWpzJm7XKXmskP8LoLczVuuMU0',
    appId: '1:757179767968:ios:94596973041ebe2c337dc5',
    messagingSenderId: '757179767968',
    projectId: 'khabi-naa',
    databaseURL: 'https://khabi-naa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'khabi-naa.firebasestorage.app',
    iosBundleId: 'com.example.secFoodalert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYR7hl3hWpzJm7XKXmskP8LoLczVuuMU0',
    appId: '1:757179767968:ios:94596973041ebe2c337dc5',
    messagingSenderId: '757179767968',
    projectId: 'khabi-naa',
    databaseURL: 'https://khabi-naa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'khabi-naa.firebasestorage.app',
    iosBundleId: 'com.example.secFoodalert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW6LEeWDgS85UxzlSZ0aHBL1hji5eDX8g',
    appId: '1:757179767968:web:0a0b77c4f807b1f5337dc5',
    messagingSenderId: '757179767968',
    projectId: 'khabi-naa',
    authDomain: 'khabi-naa.firebaseapp.com',
    databaseURL: 'https://khabi-naa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'khabi-naa.firebasestorage.app',
    measurementId: 'G-82F0BJ5TX8',
  );
}
